stages:
  - build
  - test
build_job:
  stage: build
  script:
    - echo "Iniciando o build com Gradle..."
    - ./gradlew build
test_job:
  stage: test
  script:
    - echo "Executando testes automatizados..."
    - ./gradlew test
